#!/usr/bin/env bash
# A Bash script that displays infinity sentences with sleeping
# 2 seconds between each iteration

MSG () {
	echo -e "I am invincible!!!" 
}

trap "MSG" SIGTERM

while true; do
	echo -e "To infinity and beyond"
	sleep 2
done
